version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1223
      POSTGRES_DB: Spital
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
