apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotspital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robotspital
  template:
    metadata:
      labels:
        app: robotspital
    spec:
      containers:
        - name: backend
          image: zebyan/robotspital:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: robotspital-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: robotspital-secrets
                  key: SECRET_KEY
          ports:
            - containerPort: 8000

