# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_VFwtnAvMaX28@ep-rapid-sunset-a9ni62on-pooler.gwc.azure.neon.tech/neondb?sslmode=require"
