name: CD

on:
  workflow_run:
    workflows: ["CI"]   
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig.yaml
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

      - name: Inject Kubernetes secrets
        run: |
          kubectl --kubeconfig=kubeconfig.yaml create secret generic robotspital-secrets \
            --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/
