name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          set -euxo pipefail
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $KUBECONFIG

      - name: Inject Kubernetes secrets
        run: |
          set -euxo pipefail
          kubectl create secret generic robotspital-secrets \
            --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          set -euxo pipefail
          kubectl apply -f k8s/
